services:
  # Prometheus: 指标存储
  prometheus:
    image: prom/prometheus:v3.3.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"

  # Tempo: 链路存储
  tempo:
    image: grafana/tempo:2.7.2
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml", "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/data:/var/tempo
    ports:
      - "3200:3200"   # Tempo API
      - "4317"        # 内部接收 OTEL 转发的 gRPC

  # Loki: 日志存储
  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  # OpenTelemetry Collector: 统一接收处理
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-config.yaml" ]
    volumes:
      - ./otel/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317" # gRPC 接收
      - "4318:4318" # HTTP 接收
      - "8889:8889" # Prometheus 抓取端口
    depends_on:
      - tempo
      - loki

  # Grafana: 统一展示
  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin@123
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    user: "472" # 解决部分 Linux 环境下的权限问题，472 是 grafana 默认用户 ID
    depends_on:
      - prometheus
      - tempo
      - loki