spring:
  threads:
    virtual:
      enabled: true
  task:
    # 异步任务 TaskExecutionProperties
    execution:
      thread-name-prefix: async-
      # 开启虚拟线程默认使用 SimpleAsyncTaskExecutor
      simple:
        # 若配置为 true 当达到 concurrency limit 时会抛出 TaskRejectedException 异常
        reject-tasks-when-limit-reached: false
        # -1 indicates no concurrency limit at all.
        concurrency-limit: -1
      shutdown:
        await-termination: true
        await-termination-period: 60s
    # 定时任务 TaskSchedulingProperties
    scheduling:
      thread-name-prefix: scheduling-
      # 开启虚拟线程默认使用 SimpleAsyncTaskScheduler
      simple:
        # -1 indicates no concurrency limit at all.
        concurrency-limit: -1
      shutdown:
        await-termination: true
        await-termination-period: 60s
xxl:
  job:
    enabled: true
    # 执行器通讯token
    accessToken: default_token
    # 调度器地址
    admin:
      addresses: http://127.0.0.1:9090/xxl-job-admin
    executor:
      # 执行器应用名
      app-name: ${spring.application.name}
      # 执行器日志路径
      log-path: ${user.home}/logs/xxl-job/${spring.application.name}
