apiVersion: 1
datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
  - name: Tempo
    uid: Tempo
    type: tempo
    url: http://tempo:3200