spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      connect-timeout: 10s
      timeout: 3s
      username: default
      password: 123456
  cache:
    type: redis
    redis:
      time-to-live: 30m
      cache-null-values: true
      use-key-prefix: true
      key-prefix: "cache:"
redisson:
  lazy-initialization: false
  threads: 16
  netty-threads: 32
  transport-mode: NIO
  protocol: RESP2
  lock-watchdog-timeout: 30_000
  check-lock-synced-slaves: true
  slaves-sync-timeout: 1000
  reliable-topic-watchdog-timeout: 600_000
  use-script-cache: true
  keep-pub-sub-order: true
  single:
    subscription-connection-minimum-idle-size: 1
    subscription-connection-pool-size: 50
    connection-minimum-idle-size: 24
    connection-pool-size: 64
    idle-connection-timeout: 10_000
    retry-attempts: 3
    retry-base-delay: 1000ms
    retry-max-delay: 2s