server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 20
      max: 200
    accept-count: 100
    max-connections: 8192
    connection-timeout: 5s
spring:
  application:
    name: application
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    locale: zh_CN
    locale-resolver: accept_header
  mvc:
    log-request-details: true
    static-path-pattern: /**
    webjars-path-pattern: /webjars/**
    pathmatch:
      matching-strategy: path_pattern_parser
    contentnegotiation:
      favor-parameter: true
      parameter-name: format
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 32MB
  jackson:
    timeZone: GMT+8
    default-property-inclusion: non_null
  messages:
    basename: 'i18n/messages'
    encoding: UTF-8
    cache-duration: 3600